apiVersion: 1

datasources:
  - name: JDG Postgres
    uid: jdg_postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
